[metadata]
name = xldg
version = 0.3.8
description = XLDataGraph is a library for crosslinking data analysis and visualization.
author = a-helix
long_description = file: README.md
long_description_content_type = text/markdown
license_files = LICENSE
url = https://github.com/a-helix/XLDataGraph
project_urls =
    Bug Tracker = https://github.com/a-helix/XLDataGraph/issues

[options]
package_dir =
    = xldg/src
packages = find:
include_package_data = True
python_requires = >=3.7
install_requires =
    numpy>=1.20.0
    networkx>=2.5
    matplotlib>=3.3.0
    pyCirclize>=1.6.0
    matplotlib_venn>=1.1.2

[options.packages.find]
where = xldg/src
exclude =
    tests*
    examples*
    venv*

